"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const auth_middleware_1 = require("../middleware/auth.middleware");
const tenantAuth_1 = require("../middleware/tenantAuth");
const loanController_1 = require("../controllers/loanController");
const repayment_controller_1 = require("../controllers/repayment.controller");
const router = express_1.default.Router();
router.post('/request', auth_middleware_1.protect, tenantAuth_1.tenantAuth, auth_middleware_1.allowEveryone, loanController_1.createLoanRequest);
router.post('/:id/approve', auth_middleware_1.protect, tenantAuth_1.tenantAuth, auth_middleware_1.allowTeamLeadHRManager, loanController_1.approveLoanRequest);
router.post('/:id/reject', auth_middleware_1.protect, tenantAuth_1.tenantAuth, auth_middleware_1.allowTeamLeadHRManager, loanController_1.rejectLoanRequest);
router.get('/loan-queue', auth_middleware_1.protect, tenantAuth_1.tenantAuth, auth_middleware_1.allowEveryone, loanController_1.getLoanApprovalQueue);
router.get('/activity-feed', auth_middleware_1.protect, tenantAuth_1.tenantAuth, auth_middleware_1.allowEveryone, loanController_1.getLoanActivityFeed);
router.get('/status-overview', auth_middleware_1.protect, tenantAuth_1.tenantAuth, auth_middleware_1.allowEveryone, loanController_1.getLoanStatusOverview);
router.get('/balance-overview', auth_middleware_1.protect, tenantAuth_1.tenantAuth, auth_middleware_1.allowEveryone, loanController_1.getLoanBalanceOverview);
router.post('/loan-repayment', auth_middleware_1.protect, tenantAuth_1.tenantAuth, auth_middleware_1.allowEveryone, repayment_controller_1.makeLoanRepayment);
router.get('/repayment-history', auth_middleware_1.protect, tenantAuth_1.tenantAuth, auth_middleware_1.allowEveryone, repayment_controller_1.getRepaymentHistory);
exports.default = router;
